cluster_name = "demo"
database_name = "dev"
user_name = "radhika"
instance_type = "ra3.large"
cluster_type = "multi-node"
sg = []
az = "us-east-1a"
nodes= 2
roles = []
redshift_public_access =  true
maintenance_window = "Sun:00:00-Sun:00:30"
retention_period = 7
subnet_group = "value"
